# Generated by Django 5.2.6 on 2025-09-12 09:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(help_text='Driver’s license or CDL number', max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(help_text='Truck license plate number', max_length=50, unique=True)),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=100, unique=True)),
                ('make_model', models.CharField(help_text='e.g. Volvo VNL 760', max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.JSONField(blank=True, help_text='Current location (could be coordinates or city/state).', null=True)),
                ('pickup_location', models.JSONField(help_text='Pickup location coordinates or address.')),
                ('dropoff_location', models.JSONField(help_text='Dropoff location coordinates or address.')),
                ('current_cycle_hours', models.DecimalField(decimal_places=2, default=0.0, help_text='Hours already used in the 70hr/8day cycle.', max_digits=5)),
                ('route_distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('route_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('route_data', models.JSONField(blank=True, help_text='Full response from the map API (waypoints, geometry, etc.).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.driver')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='api.truck')),
            ],
        ),
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('grid_data', models.JSONField(help_text='Array of duty status segments for the 24-hour log.')),
                ('total_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.trip')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
