from rest_framework import viewsets
from .models import Driver, Truck, Trip, LogSheet
from .serializers import DriverSerializer, TruckSerializer, TripSerializer, LogSheetSerializer

class DriverViewSet(viewsets.ModelViewSet):
    queryset = Driver.objects.all().order_by("-created_at")
    serializer_class = DriverSerializer

class TruckViewSet(viewsets.ModelViewSet):
    queryset = Truck.objects.all().order_by("-created_at")
    serializer_class = TruckSerializer

class TripViewSet(viewsets.ModelViewSet):
    queryset = Trip.objects.all().order_by("-created_at")
    serializer_class = TripSerializer

class LogSheetViewSet(viewsets.ReadOnlyModelViewSet):
    # usually logs are read-only; generated by system logic
    queryset = LogSheet.objects.all().order_by("date")
    serializer_class = LogSheetSerializer
